### PR TITLE
TMDM-14656 [CVE] - Update XercesImpl to 2.12.0

### PR DESCRIPTION
**Pull request by lpw82gf**
https://jira.talendforge.org/browse/TMDM-14656
**What is the current behavior?** (You should also link to an open issue here)
- Using version of 2.9.1 which has CVE risk

**What is the new behavior?**
- Upgrade to 2.12.0

**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

File: org.talend.mdm.base/pom.xml [hunk 1]
```diff
@@ -938,8 +938,7 @@
             <dependency>
                 <groupId>xml-apis</groupId>
                 <artifactId>xml-apis</artifactId>
-                <version>1.0.b2</version>
-                <scope>provided</scope>
```
Comment (lpw82gf) [inline org.talend.mdm.base/pom.xml:942]: After upgrade to 1.4.01 version, we should include that JAR into talendmdm.war to avoid start up issue.
```
27-May-2020 10:45:34.647 SEVERE [main] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class [org.springframework.web.util.Log4jConfigListener]
	java.lang.NoClassDefFoundError: org/w3c/dom/ElementTraversal
		at java.lang.ClassLoader.defineClass1(Native Method)
		at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
         ...
```
